export const RECV_ARTICLE_DATA = 'RECV_ARTICLE_DATA'
export const RECV_ARTICLE_ERROR = 'RECV_ARTICLE_ERROR'
export const RECV_SINGLE_ARTICLE_DATA = 'RECV_SINGLE_ARTICLE_DATA'
export const REQ_ARTICLE_DATA = 'REQ_ARTICLE_DATA'
